-- Simulation trading platform account / order / position schema for SQLite
-- Run via: ib init-db
--
-- Money and quantity columns are INTEGER micro-units (1_000_000 per unit).
-- The app scales Decimal values by 10^6 before storing and divides on read,
-- so six-decimal fixed-point values round-trip exactly with no binary
-- floating-point error.

CREATE TABLE CONTRACTS (
    CONID      INTEGER       NOT NULL,
    SYMBOL     TEXT          NOT NULL,
    SEC_TYPE   TEXT          NOT NULL,  -- STK / OPT / FUT / CASH / BAG
    EXCHANGE   TEXT          DEFAULT 'SMART' NOT NULL,
    CURRENCY   TEXT          DEFAULT 'USD' NOT NULL,
    LOCAL_SYMBOL TEXT,
    MULTIPLIER INTEGER       DEFAULT 1000000 NOT NULL,
    CREATED_AT TEXT          DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_CONTRACTS PRIMARY KEY (CONID),
    CONSTRAINT UQ_CONTRACTS UNIQUE (SYMBOL, SEC_TYPE, EXCHANGE, CURRENCY),
    CONSTRAINT CK_CONTRACTS_MULTIPLIER CHECK (MULTIPLIER > 0),
    CONSTRAINT CK_CONTRACTS_SEC CHECK (SEC_TYPE IN ('STK','OPT','FUT','CASH','BAG','IND'))
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID   TEXT         NOT NULL,       -- e.g. U1234567
    ACCOUNT_TYPE TEXT         DEFAULT 'MARGIN' NOT NULL,  -- CASH / MARGIN / IRA
    CURRENCY     TEXT         DEFAULT 'USD' NOT NULL,
    STATUS       TEXT         DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TEXT         DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT CK_ACCOUNTS_TYPE CHECK (ACCOUNT_TYPE IN ('CASH','MARGIN','IRA')),
    CONSTRAINT CK_ACCOUNTS_STATUS CHECK (STATUS IN ('ACTIVE','CLOSED','RESTRICTED'))
);

-- Simulation order states, compatible with common broker terminology
CREATE TABLE ORDERS (
    PERM_ID        INTEGER       DEFAULT NULL,  -- assigned on acceptance
    ORDER_ID       INTEGER       NOT NULL,      -- client-side id
    ACCOUNT_ID     TEXT          NOT NULL,
    CONID          INTEGER       NOT NULL,
    SIDE           TEXT          NOT NULL,      -- BUY / SELL
    ORDER_TYPE     TEXT          NOT NULL,      -- MKT / LMT / STP / STP_LMT
    LMT_PRICE      INTEGER,
    AUX_PRICE      INTEGER,                    -- stop price
    TOTAL_QUANTITY INTEGER       NOT NULL,
    FILLED_QUANTITY INTEGER      DEFAULT 0 NOT NULL,
    AVG_FILL_PRICE  INTEGER,
    TIF            TEXT          DEFAULT 'DAY' NOT NULL,  -- DAY/GTC/IOC/OPG
    OUTSIDE_RTH    INTEGER       DEFAULT 0 NOT NULL,
    STATUS         TEXT          DEFAULT 'PendingSubmit' NOT NULL,
    PARENT_ORDER_ID INTEGER,
    CREATED_AT     TEXT          DEFAULT (datetime('now')) NOT NULL,
    UPDATED_AT     TEXT          DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID, ACCOUNT_ID),
    CONSTRAINT UQ_ORDERS_FILL_REF UNIQUE (ORDER_ID, ACCOUNT_ID, CONID, SIDE),
    CONSTRAINT FK_ORDERS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_ORDERS_CONTRACT FOREIGN KEY (CONID) REFERENCES CONTRACTS (CONID),
    CONSTRAINT CK_ORDERS_SIDE CHECK (SIDE IN ('BUY','SELL')),
    CONSTRAINT CK_ORDERS_TYPE CHECK (ORDER_TYPE IN ('MKT','LMT','STP','STP_LMT')),
    CONSTRAINT CK_ORDERS_TIF CHECK (TIF IN ('DAY','GTC','IOC','OPG')),
    CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN
        ('PendingSubmit','Submitted','PreSubmitted','Filled','Cancelled','Inactive')),
    CONSTRAINT CK_ORDERS_QTY CHECK (
        TOTAL_QUANTITY > 0 AND FILLED_QUANTITY >= 0 AND FILLED_QUANTITY <= TOTAL_QUANTITY
    ),
    CONSTRAINT CK_ORDERS_AVG_PRICE CHECK (AVG_FILL_PRICE IS NULL OR AVG_FILL_PRICE > 0)
);

CREATE TABLE FILLS (
    EXEC_ID    TEXT          NOT NULL,
    ORDER_ID   INTEGER       NOT NULL,
    ACCOUNT_ID TEXT          NOT NULL,
    CONID      INTEGER       NOT NULL,
    SIDE       TEXT          NOT NULL,
    QUANTITY   INTEGER       NOT NULL,
    PRICE      INTEGER       NOT NULL,
    EXEC_TIME  TEXT          DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_FILLS PRIMARY KEY (EXEC_ID),
    CONSTRAINT FK_FILLS_ORDER FOREIGN KEY (ORDER_ID, ACCOUNT_ID)
        REFERENCES ORDERS (ORDER_ID, ACCOUNT_ID),
    CONSTRAINT FK_FILLS_ORDER_REF FOREIGN KEY (ORDER_ID, ACCOUNT_ID, CONID, SIDE)
        REFERENCES ORDERS (ORDER_ID, ACCOUNT_ID, CONID, SIDE),
    CONSTRAINT CK_FILLS_QTY_PRICE CHECK (QUANTITY > 0 AND PRICE > 0),
    CONSTRAINT CK_FILLS_SIDE CHECK (SIDE IN ('BUY','SELL'))
);

CREATE INDEX IX_FILLS_ORDER ON FILLS (ORDER_ID, ACCOUNT_ID);

-- Simulation position snapshot per account/contract/currency
CREATE TABLE POSITIONS (
    ACCOUNT_ID  TEXT          NOT NULL,
    CONID       INTEGER       NOT NULL,
    POSITION    INTEGER       NOT NULL,   -- signed micro-units: long +, short -
    AVG_COST    INTEGER,
    MARKET_PRICE INTEGER,
    UPDATED_AT  TEXT          DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_POSITIONS PRIMARY KEY (ACCOUNT_ID, CONID),
    CONSTRAINT FK_POS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_POS_CONTRACT FOREIGN KEY (CONID) REFERENCES CONTRACTS (CONID)
);

-- Cash balances per simulation account currency, in micro-units
CREATE TABLE CASH_BALANCES (
    ACCOUNT_ID  TEXT          NOT NULL,
    CURRENCY    TEXT          NOT NULL,
    CASH        INTEGER       DEFAULT 0 NOT NULL,
    UPDATED_AT  TEXT          DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_CASH PRIMARY KEY (ACCOUNT_ID, CURRENCY),
    CONSTRAINT FK_CASH_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
);
