-- IBKR-style account / order / position schema for Oracle Database
-- Run via: ib init-db

CREATE TABLE CONTRACTS (
    CONID      NUMBER(10)      NOT NULL,
    SYMBOL     VARCHAR2(16)    NOT NULL,
    SEC_TYPE   VARCHAR2(8)     NOT NULL,  -- STK / OPT / FUT / CASH / BAG
    EXCHANGE   VARCHAR2(32)    DEFAULT 'SMART' NOT NULL,
    CURRENCY   VARCHAR2(3)     DEFAULT 'USD' NOT NULL,
    LOCAL_SYMBOL VARCHAR2(32),
    MULTIPLIER NUMBER          DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CONTRACTS PRIMARY KEY (CONID),
    CONSTRAINT UQ_CONTRACTS UNIQUE (SYMBOL, SEC_TYPE, EXCHANGE, CURRENCY),
    CONSTRAINT CK_CONTRACTS_SEC CHECK (SEC_TYPE IN ('STK','OPT','FUT','CASH','BAG','IND'))
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID   VARCHAR2(16)   NOT NULL,       -- e.g. U1234567
    ACCOUNT_TYPE VARCHAR2(8)    DEFAULT 'MARGIN' NOT NULL,  -- CASH / MARGIN / IRA
    CURRENCY     VARCHAR2(3)    DEFAULT 'USD' NOT NULL,
    STATUS       VARCHAR2(12)   DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT CK_ACCOUNTS_TYPE CHECK (ACCOUNT_TYPE IN ('CASH','MARGIN','IRA')),
    CONSTRAINT CK_ACCOUNTS_STATUS CHECK (STATUS IN ('ACTIVE','CLOSED','RESTRICTED'))
);

-- IBKR order states
CREATE TABLE ORDERS (
    PERM_ID        NUMBER(12)      DEFAULT NULL,  -- assigned on acceptance
    ORDER_ID       NUMBER(10)      NOT NULL,      -- client-side id
    ACCOUNT_ID     VARCHAR2(16)    NOT NULL,
    CONID          NUMBER(10)      NOT NULL,
    SIDE           VARCHAR2(4)     NOT NULL,      -- BUY / SELL
    ORDER_TYPE     VARCHAR2(8)     NOT NULL,      -- MKT / LMT / STP / STP_LMT
    LMT_PRICE      NUMBER(18,6),
    AUX_PRICE      NUMBER(18,6),                  -- stop price
    TOTAL_QUANTITY NUMBER(18,6)    NOT NULL,
    FILLED_QUANTITY NUMBER(18,6)   DEFAULT 0 NOT NULL,
    AVG_FILL_PRICE  NUMBER(18,6),
    TIF            VARCHAR2(4)     DEFAULT 'DAY' NOT NULL,  -- DAY/GTC/IOC/OPG
    OUTSIDE_RTH    NUMBER(1)       DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(16)    DEFAULT 'PendingSubmit' NOT NULL,
    PARENT_ORDER_ID NUMBER(10),
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID, ACCOUNT_ID),
    CONSTRAINT FK_ORDERS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_ORDERS_CONTRACT FOREIGN KEY (CONID) REFERENCES CONTRACTS (CONID),
    CONSTRAINT CK_ORDERS_SIDE CHECK (SIDE IN ('BUY','SELL')),
    CONSTRAINT CK_ORDERS_TYPE CHECK (ORDER_TYPE IN ('MKT','LMT','STP','STP_LMT')),
    CONSTRAINT CK_ORDERS_TIF CHECK (TIF IN ('DAY','GTC','IOC','OPG')),
    CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN
        ('PendingSubmit','Submitted','PreSubmitted','Filled','Cancelled','Inactive')),
    CONSTRAINT CK_ORDERS_QTY CHECK (TOTAL_QUANTITY > 0 AND FILLED_QUANTITY >= 0)
);

CREATE TABLE FILLS (
    EXEC_ID    VARCHAR2(24)    NOT NULL,
    ORDER_ID   NUMBER(10)      NOT NULL,
    ACCOUNT_ID VARCHAR2(16)    NOT NULL,
    CONID      NUMBER(10)      NOT NULL,
    SIDE       VARCHAR2(4)     NOT NULL,
    QUANTITY   NUMBER(18,6)    NOT NULL,
    PRICE      NUMBER(18,6)    NOT NULL,
    EXEC_TIME  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_FILLS PRIMARY KEY (EXEC_ID),
    CONSTRAINT FK_FILLS_ORDER FOREIGN KEY (ORDER_ID, ACCOUNT_ID)
        REFERENCES ORDERS (ORDER_ID, ACCOUNT_ID),
    CONSTRAINT CK_FILLS_SIDE CHECK (SIDE IN ('BUY','SELL'))
);

CREATE INDEX IX_FILLS_ORDER ON FILLS (ORDER_ID, ACCOUNT_ID);

-- Real-time position snapshot per account/contract/currency
CREATE TABLE POSITIONS (
    ACCOUNT_ID  VARCHAR2(16)   NOT NULL,
    CONID       NUMBER(10)     NOT NULL,
    POSITION    NUMBER(18,6)   NOT NULL,   -- signed: long +, short -
    AVG_COST    NUMBER(18,6),
    MARKET_PRICE NUMBER(18,6),
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POSITIONS PRIMARY KEY (ACCOUNT_ID, CONID),
    CONSTRAINT FK_POS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
    CONSTRAINT FK_POS_CONTRACT FOREIGN KEY (CONID) REFERENCES CONTRACTS (CONID)
);

-- Cash balances per account currency (IB reports one row per currency)
CREATE TABLE CASH_BALANCES (
    ACCOUNT_ID  VARCHAR2(16)   NOT NULL,
    CURRENCY    VARCHAR2(3)    NOT NULL,
    CASH        NUMBER(18,6)   DEFAULT 0 NOT NULL,
    UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CASH PRIMARY KEY (ACCOUNT_ID, CURRENCY),
    CONSTRAINT FK_CASH_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
);
