-- User registration, login and session tables for the simulation platform

CREATE TABLE USERS (
    USER_ID        TEXT     NOT NULL,
    EMAIL          TEXT     NOT NULL,
    PASSWORD_HASH  TEXT     NOT NULL,
    EMAIL_VERIFIED INTEGER  DEFAULT 0 NOT NULL,
    STATUS         TEXT     DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT     TEXT     DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_VERIFIED CHECK (EMAIL_VERIFIED IN (0, 1)),
    CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE SESSIONS (
    SESSION_ID  TEXT NOT NULL,
    USER_ID     TEXT NOT NULL,
    TOKEN_HASH  TEXT NOT NULL,
    EXPIRES_AT  TEXT NOT NULL,
    CREATED_AT  TEXT DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_SESSIONS PRIMARY KEY (SESSION_ID),
    CONSTRAINT UQ_SESSIONS_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE INDEX IX_SESSIONS_USER ON SESSIONS (USER_ID);
