-- User registration, login and session tables for the simulation platform

CREATE TABLE USERS (
    USER_ID        VARCHAR2(36)  NOT NULL,
    EMAIL          VARCHAR2(320) NOT NULL,
    PASSWORD_HASH  VARCHAR2(255) NOT NULL,
    EMAIL_VERIFIED NUMBER(1)     DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(12)  DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_VERIFIED CHECK (EMAIL_VERIFIED IN (0, 1)),
    CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE SESSIONS (
    SESSION_ID  VARCHAR2(36) NOT NULL,
    USER_ID     VARCHAR2(36) NOT NULL,
    TOKEN_HASH  VARCHAR2(64) NOT NULL,
    EXPIRES_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SESSIONS PRIMARY KEY (SESSION_ID),
    CONSTRAINT UQ_SESSIONS_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE INDEX IX_SESSIONS_USER ON SESSIONS (USER_ID);
