-- Email verification tokens for the Resend adapter.
-- One row per outstanding verification email. The raw token is only
-- ever sent by email while the database keeps its SHA-256 hash.

CREATE TABLE IF NOT EXISTS EMAIL_VERIFICATIONS (
    VERIFICATION_ID TEXT NOT NULL,
    USER_ID         TEXT NOT NULL,
    TOKEN_HASH      TEXT NOT NULL,
    EXPIRES_AT      TEXT NOT NULL,
    CREATED_AT      TEXT DEFAULT (datetime('now')) NOT NULL,
    CONSTRAINT PK_EMAIL_VERIFICATIONS PRIMARY KEY (VERIFICATION_ID),
    CONSTRAINT UQ_EMAIL_VERIFICATIONS_TOKEN UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_EMAIL_VERIFICATIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE INDEX IF NOT EXISTS IX_EMAIL_VERIFICATIONS_USER ON EMAIL_VERIFICATIONS (USER_ID);
